### PR TITLE
Add 2 templates

### PR DESCRIPTION
**Pull request by Fluoflo**

### CODE REVIEW

**Comment by lexoyo** [comment]
hey @Fluoflo thank you !
I need you to do 2 things before I can accept the pull request:
- add a screenshot, with the same name and size (678x336) as the other templates, like [this one](https://github.com/Fluoflo/silex-templates/blob/30f792448f4170055bf4451311872f83d3111e54/templates/eco1/screenshot-678x336.png) - this is because the templates appear on silex website
- rename your index.html to editable.html and [publish your website as explained here](https://github.com/silexlabs/Silex/issues/238) so that there is a "clean" index.html beside your editable.html (if this is too confusing, I guess you could skip this step)

**Comment by Fluoflo** [comment]
Committed screenshots and change idnex -> editable but I'm not sure where the "clean" indexes come from

**Comment by lexoyo** [comment]
You are supposed to open file > settings > publication settings, and select a folder as shown here
https://github.com/silexlabs/Silex/issues/238

Select your root folder, where your editable.html is

**Comment by Fluoflo** [comment]
Ok, got it. PR squashed & ready to merge!

**Pull request merged**
